function wait(sec) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      reject("throw Error! ");
    }, sec * 1000);
  });
}

async function myAsyncFunc() {
  console.log(new Date());
 
  const result2 = await wait(2).catch((e) => {
    console.error(e);
  });
  console.log(new Date());
  console.log(result2);
}

const result = myAsyncFunc();